"""Anthropic Models API shapes for configured Claude-visible aliases."""

from __future__ import annotations

from fnmatch import fnmatchcase
from typing import TYPE_CHECKING
from urllib.parse import quote, unquote_to_bytes

from .exceptions import ConversionError

if TYPE_CHECKING:
    from collections.abc import Mapping

UNKNOWN_MODEL_CREATED_AT = "1970-01-01T00:00:00Z"
AUTOMATIC_MODEL_ALIAS_PREFIX = "claude-proxy-"
_DEFAULT_PAGE_LIMIT = 20
_MIN_PAGE_LIMIT = 1
_MAX_PAGE_LIMIT = 1000


def automatic_model_alias(upstream_model: str) -> str:
    """Return a reversible Claude-compatible alias for an upstream model ID."""
    encoded = quote(upstream_model, safe="-._~")
    return f"{AUTOMATIC_MODEL_ALIAS_PREFIX}{encoded}"


def automatic_upstream_model(alias: str) -> str | None:
    """Decode an alias generated by :func:`automatic_model_alias`."""
    if not alias.startswith(AUTOMATIC_MODEL_ALIAS_PREFIX):
        return None
    encoded = alias.removeprefix(AUTOMATIC_MODEL_ALIAS_PREFIX)
    if not encoded:
        return None
    try:
        upstream_model = unquote_to_bytes(encoded).decode()
    except UnicodeDecodeError:
        return None
    if automatic_model_alias(upstream_model) != alias:
        return None
    return upstream_model


def openai_model_aliases(
    payload: object,
    *,
    include: tuple[str, ...],
    exclude: tuple[str, ...],
) -> dict[str, str]:
    """Translate a standard OpenAI model list into Claude-visible aliases."""
    if not isinstance(payload, dict):
        raise ConversionError("OpenAI model list must be an object")
    object_type = payload.get("object")
    if object_type is not None and object_type != "list":
        raise ConversionError("OpenAI model list has an invalid object type")
    data = payload.get("data")
    if not isinstance(data, list):
        raise ConversionError("OpenAI model list data must be an array")

    aliases: dict[str, str] = {}
    for item in data:
        if not isinstance(item, dict):
            raise ConversionError("OpenAI model list entries must be objects")
        model_id = item.get("id")
        if not isinstance(model_id, str) or not model_id:
            raise ConversionError("OpenAI model list entries must have non-empty string IDs")
        if not any(fnmatchcase(model_id, pattern) for pattern in include):
            continue
        if any(fnmatchcase(model_id, pattern) for pattern in exclude):
            continue
        display_name = item.get("display_name")
        if not isinstance(display_name, str) or not display_name:
            display_name = model_id
        aliases.setdefault(automatic_model_alias(model_id), display_name)
    return aliases


def model_info(model_id: str, display_name: str) -> dict[str, object]:
    """Build one Anthropic SDK-compatible model object with unknown release date."""
    return {
        "id": model_id,
        "display_name": display_name,
        "type": "model",
        "created_at": UNKNOWN_MODEL_CREATED_AT,
    }


def _page_limit(query: Mapping[str, str]) -> int:
    raw_limit = query.get("limit")
    if raw_limit is None:
        return _DEFAULT_PAGE_LIMIT
    try:
        limit = int(raw_limit)
    except ValueError as exc:
        raise ConversionError("Model list limit must be an integer") from exc
    if not _MIN_PAGE_LIMIT <= limit <= _MAX_PAGE_LIMIT:
        raise ConversionError("Model list limit must be between 1 and 1000")
    return limit


def _cursor_index(model_ids: list[str], cursor: str, name: str) -> int:
    try:
        return model_ids.index(cursor)
    except ValueError as exc:
        raise ConversionError(f"Unknown model pagination {name}: {cursor!r}") from exc


def model_page(
    models: Mapping[str, str],
    query: Mapping[str, str],
) -> dict[str, object]:
    """Apply Anthropic cursor pagination to configured model aliases."""
    after_id = query.get("after_id")
    before_id = query.get("before_id")
    if after_id and before_id:
        raise ConversionError("after_id and before_id cannot be used together")

    limit = _page_limit(query)
    model_ids = list(models)
    if before_id:
        end = _cursor_index(model_ids, before_id, "before_id")
        start = max(0, end - limit)
        has_more = start > 0
    else:
        start = _cursor_index(model_ids, after_id, "after_id") + 1 if after_id else 0
        end = min(len(model_ids), start + limit)
        has_more = end < len(model_ids)

    selected_ids = model_ids[start:end]
    return {
        "data": [model_info(model_id, models[model_id]) for model_id in selected_ids],
        "has_more": has_more,
        "first_id": selected_ids[0] if selected_ids else None,
        "last_id": selected_ids[-1] if selected_ids else None,
    }
